//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 04:31:22 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.createpocartproducer.com/createpo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.fuze.po.PurchaseOrderAppServices.bean;
